[package]
name = "llmbench"
version = "0.1.0"
edition = "2024"

[dependencies]
ansi-width = "0.1.0"
ascii_table = { version = "4.0.8", features = ["color_codes"] }
bon = "3.8.1"
clap = { version = "4.5.51", features = ["derive", "env"] }
derive_more = { version = "2.0.1", features = ["full"] }
dotenvy = { version = "0.15.7", features = ["clap", "cli"] }
error-stack = { version = "0.6.0", features = ["hooks", "spantrace"] }
glob = "0.3.3"
linkme = "0.3.35"
openrouter = { path = "vendor/openrouter" }
ordered-float = { version = "5.1.0", features = ["serde"] }
owo-colors = "4.2.3"
pad = "0.1.6"
paste = "1.0.15"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
textwrap = "0.16.2"
# openrouter = "0.2.0"
thiserror = "2.0.17"
tokio = { version = "1.48.0", features = ["full"] }
toml = "0.9.8"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", features = ["env-filter"] }
twox-hash = "2.1.2"
