models = [
    # free models
    # "cognitivecomputations/dolphin-mistral-24b-venice-edition:free",
    # "deepseek/deepseek-chat-v3.1:free",
    # "deepseek/deepseek-r1-distill-llama-70b:free",
    # "deepseek/deepseek-r1:free",
    # "google/gemini-2.0-flash-exp:free",
    # "google/gemma-3-12b-it:free",
    # "google/gemma-3-27b-it:free",
    # "kwaipilot/kat-coder-pro:free",
    # "meta-llama/llama-3.2-3b-instruct:free",
    # "meta-llama/llama-3.3-70b-instruct:free",
    # "microsoft/mai-ds-r1:free",
    # "mistralai/mistral-7b-instruct:free",
    # "mistralai/mistral-nemo:free",
    # "mistralai/mistral-small-3.2-24b-instruct:free",
    # "moonshotai/kimi-k2:free",
    # "nvidia/nemotron-nano-12b-v2-vl:free",
    # "nvidia/nemotron-nano-9b-v2:free",
    # "openai/gpt-oss-20b:free",
    # "qwen/qwen3-235b-a22b:free",
    # "qwen/qwen3-30b-a3b:free",
    # "qwen/qwen3-coder:free",
    # "tngtech/deepseek-r1t2-chimera:free",
    # "z-ai/glm-4.5-air:free",

    # paid models
    # "anthropic/claude-haiku-4.5",
    # "anthropic/claude-opus-4.1",
    # "anthropic/claude-sonnet-4",
    # "anthropic/claude-sonnet-4.5",
    # "baidu/ernie-4.5-21b-a3b",
    # "baidu/ernie-4.5-21b-a3b-thinking",
    # "baidu/ernie-4.5-vl-28b-a3b",
    # "deepseek/deepseek-chat-v3.1",
    # "deepseek/deepseek-prover-v2",
    # "deepseek/deepseek-r1-0528",
    # "deepseek/deepseek-r1-0528-qwen3-8b",
    # "deepseek/deepseek-r1-distill-llama-70b",
    # "deepseek/deepseek-v3.1-terminus",
    # "deepseek/deepseek-v3.2-exp",
    # "google/gemini-2.0-flash-001",
    # "google/gemini-2.5-flash",
    "google/gemini-2.5-flash-lite",
    # "google/gemini-2.5-pro",
    # "google/gemma-3n-e4b-it",
    # "meta-llama/llama-3-70b-instruct",
    # "meta-llama/llama-3.3-70b-instruct",
    # "meta-llama/llama-4-maverick",
    # "meta-llama/llama-4-scout",
    "microsoft/phi-3.5-mini-128k-instruct",
    "microsoft/phi-3-mini-128k-instruct",
    # "microsoft/phi-4",
    # "microsoft/phi-4-multimodal-instruct",
    # "microsoft/phi-4-reasoning-plus",
    # "minimax/minimax-m1",
    # "minimax/minimax-m2",
    # "mistralai/codestral-2508",
    # "mistralai/devstral-medium",
    # "mistralai/devstral-small",
    # "mistralai/mistral-7b-instruct-v0.3",
    # "mistralai/mistral-medium-3.1",
    # "mistralai/mistral-small-3.2-24b-instruct",
    # "mistralai/voxtral-small-24b-2507",
    # "moonshotai/kimi-dev-72b",
    # "moonshotai/kimi-k2",
    # "moonshotai/kimi-k2-0905",
    # "moonshotai/kimi-k2-thinking",
    # "moonshotai/kimi-linear-48b-a3b-instruct",
    # "nousresearch/hermes-4-405b",
    # "nousresearch/hermes-4-70b",
    # "nvidia/llama-3.1-nemotron-ultra-253b-v1",
    # "nvidia/llama-3.3-nemotron-super-49b-v1.5",
    # "nvidia/nemotron-nano-12b-v2-vl",
    # "nvidia/nemotron-nano-9b-v2",
    "openai/gpt-4.1-nano",
    # "openai/gpt-4o-mini",
    # "openai/gpt-5.1",
    # "openai/gpt-5.1-chat",
    # "openai/gpt-5.1-codex",
    # "openai/gpt-5.1-codex-mini",
    # "qwen/qwen3-235b-a22b",
    # "qwen/qwen3-235b-a22b-thinking-2507",
    # "qwen/qwen3-coder",
    # "qwen/qwen3-coder-flash",
    # "qwen/qwen3-coder-plus",
    # "qwen/qwen3-max",
    # "qwen/qwen3-next-80b-a3b-instruct",
    # "qwen/qwen3-next-80b-a3b-thinking",
    # "qwen/qwen3-vl-8b-thinking",
    # "x-ai/grok-3-mini",
    # "x-ai/grok-4",
    # "x-ai/grok-4-fast",
    # "x-ai/grok-code-fast-1",
    # "z-ai/glm-4-32b",
    # "z-ai/glm-4-32b",
    # "z-ai/glm-4.5",
    # "z-ai/glm-4.5-air",
    # "z-ai/glm-4.5v",
    # "z-ai/glm-4.6",
    # "mistralai/ministral-8b",
]
